steps:
steps:
- name: 'gcr.io/cloudfunctions/python311'
  args: ['/bin/bash', '-c', 'gcloud alpha functions call fs-ps-4-mdv --region europe-west3 --data="{ \"name\": \"Madhav!\" }"']
- name: maven:3.8.3-openjdk-17
  entrypoint: mvn
  args:
    - clean
    - install
options:
  logging: CLOUD_LOGGING_ONLY
