name: Invoke Cloud Function

on:
  push:
    branches:
      - main

jobs:
  invoke-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Invoke Cloud Function
        run: |
          gcloud functions call fs-ps-4-mdv \
            --region europe-west3 \
            --data '{"name": "Hello from GitHub Actions!"}'
