name: Invoke Cloud Function

on:
  push:
    branches:
      - master

jobs:
  invoke-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Cloud Function
        run: |
          curl -X POST https://europe-west3-hip-graph-339211.cloudfunctions.net/fs-ps-4-mdv \
          -H "Authorization: Bearer YOUR_API_KEY" \
          -d '{"message": "Triggered from GitHub Actions"}'
